FROM node
MAINTAINER Grayden Shand graydenshand@gmail.com

# Install packages
# --------------
RUN apt-get update -y && \
    apt-get install -y python3-venv \
    python3-pip \
    python3-dev \
    locales locales-all
RUN pip3 install --upgrade pip

RUN npm install -g npm \ 
	npm install -g ember-cli

# Set up Env
# ----------
## Set the locale
ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE en_US:en 
ENV LANG=en_US.UTF-8

## Copy app
RUN mkdir /home/chat
WORKDIR /home/chat
COPY requirements.txt /home/chat/requirements.txt
RUN pip3 install -r requirements.txt
COPY . /home/chat/


## Build js
WORKDIR /home/chat/app/client/app/
RUN ember build -prod
WORKDIR /home/chat


# Run app
# ------- gevent server (socket io)
ENTRYPOINT ["python3"]
CMD ["main.py"]