version: '3.1'

services:  
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    image: chat-web:production
    ports:
      - 5000:5000
    restart: always
    environment:
      - DATABASE_URL=postgres://localhost:5432/chat